# Example configmap that mounts a .zshrc to /home/user/.zshrc
# NOTE: You must apply this configmap to the same namespace as your web terminal, i.e. `oc apply ./zshrc-configmap.yaml -n <namespace>`
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-zshrc
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user/
data:
  .zshrc: |
    # Needed if user wants to get some extra defaults from WTO's zshrc
    source /tmp/initial_config/.zshrc
    
    # User's personal ZSHRC goes here
    ## Lines configured by zsh-newuser-install
    HISTFILE=~/.histfile
    HISTSIZE=1000
    SAVEHIST=1000
    setopt appendhistory autocd extendedglob notify
    # End of lines configured by zsh-newuser-install
    # The following lines were added by compinstall
    zstyle :compinstall filename '/home/user/.zshrc'
    
    autoload -Uz compinit
    compinit
    ## End of lines added by compinstall
    
    ## Alias
    ## Cat alias
    alias cat="bat -p"
    
    ## Grep alias (ripgrep)
    alias grep="rg"
    
    ## Oh My ZSH
    # Path to your Oh My Zsh installation.
    export ZSH="$HOME/.oh-my-zsh"
    # Set ZSH theme
    ZSH_THEME="avit"
    
    # Which plugins would you like to load?
    # Standard plugins can be found in $ZSH/plugins/
    # Custom plugins may be added to $ZSH_CUSTOM/plugins/
    # Example format: plugins=(rails git textmate ruby lighthouse)
    # Add wisely, as too many plugins slow down shell startup.
    plugins=(git zsh-autosuggestions)
    
    source $ZSH/oh-my-zsh.sh
    
